#!/bin/bash

TESTDIR=/xs
MODULE=srvfs
FSNAME=srvfs

mkdir -p $TESTDIR

echo "unmounting"
umount $TESTDIR

echo "removing module"
rmmod $MODULE

echo "inserting module"
insmod kernel/$MODULE.ko

echo "mounting"
mount none $TESTDIR -t $FSNAME

echo "listing"
ls -la $TESTDIR
